modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "quitefishing"
version = "${version}"
displayName = "Quite Fishing"
authors="${modAuthor}"
credits="${modCredits}"
description = '''
${modDescription}
'''
logoFile = "assets/quitefishing/icon.png"

[[dependencies.quitefishing]]
modId = "neoforge"
type = "required"
versionRange = "[20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.quitefishing]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"


[[mixins]]
config = "quitefishing.mixins.json"
